apply plugin: 'com.android.application'

android {
    namespace 'com.next2026.fakedriverstation'
    compileSdk 34

    defaultConfig {
        applicationId "com.next2026.fakedriverstation"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
